### ISSUE TITLE
Verificar se ID_SERVIDOR_PORTAL é mantido para o mesmo servidor ao longo dos meses

### ISSUE THREAD

**Issue by s-holmes** [npi-ufc-qxd/dados-abertos#1]

**Comment by crislanio** [comment]
O ID É O MESMO EM TODAS AS TABELAS PARA UM DETERMINADO MÊS PORÉM EM MESES DIFERENTES ELE MUDA PARA A MESMA PESSOA.

EXEMPLO: EM 2015, A PESSOA PAULO JOSE DOS REIS SOUZA TEM 2 REGISTROS NA TABELA HONORÁRIOS COM O ID 1021618 (NA TABELA CADASTRO ELE TEM O MESMO ID PARA ESSE MÊS 1).
NO MÊS 3, PESSOA PAULO JOSE DOS REIS SOUZA APARECE EM 2 REGISTROS NA TABELA HONORÁRIOS COM O ID 1011758, PARA O MÊS 3.

EM 2017, MÊS 1 PAULO JOSE DOS REIS SOUZA TEM O ID 1076463 NA TABELA HONORÁRIOS E CADASTRO.

No mês 02 do ano de 2015 a servidora Maria Vital da Rocha tem id_servidor_portal igual a 1139531 e no mês 03 tem o mesmo igual a 1377460 na tabela honorários, remuneração.

**Comment by s-holmes** [comment]
Identificar o motivo da mudança do ID_SERVIDOR_PORTAL ao longo dos meses
Fazer teste com Ticiana Linhares e Vivane Menezes

**Comment by crislanio** [comment]
Os testes com as professores Ticiana e Viviane estão logo abaixo. Como observamos o Id_SERVIDOR_PORTAL é o mesmo.


ANO DE 2017
MÊS 01
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 294415, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 294416, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 301716, dtype: object

Id_SERVIDOR_PORTAL                      1076463
NOME                  PAULO JOSE DOS REIS SOUZA
DESCRICAO_CARGO                             NaN
Name: 53309, dtype: object



MÊS 02
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 292766, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 292767, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 300032, dtype: object





ANO DE 2016
MÊS 01
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 308871, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 308872, dtype: object


MÊS 02
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 310367, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 310368, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 318033, dtype: object

MÊS 03
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 307649, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 307650, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 315258, dtype: object


MÊS 04
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 305259, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 305260, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 312818, dtype: object


MÊS 05
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 303626, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 303627, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 311135, dtype: object


MÊS 06
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 302116, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 302117, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 309598, dtype: object


MÊS 07
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 300842, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 300843, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 308287, dtype: object


MÊS 08
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 299254, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 299255, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 306671, dtype: object


MÊS 09
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 298001, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 298002, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 305381, dtype: object


MÊS 10
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 296832, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 296833, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 304194, dtype: object


MÊS 11
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 295983, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 295984, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 303321, dtype: object


MÊS 12
Id_SERVIDOR_PORTAL                     1419351
NOME                  MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO                            NaN
Name: 295564, dtype: object
Id_SERVIDOR_PORTAL                             1419351
NOME                          MARIA VIVIANE DE MENEZES
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 295565, dtype: object
Id_SERVIDOR_PORTAL                             1429741
NOME                  TICIANA LINHARES COELHO DA SILVA
DESCRICAO_CARGO       PROFESSOR DO MAGISTERIO SUPERIOR
Name: 302894, dtype: object

para testar a veracidade dos dados crie um arquivo .py como mostrado abaixo execute:

# -*- coding: UTF-8 -*-
import csv
import pandas as pd
import sys
data = pd.read_csv('endereço/201Y/201YMM_Servidores/201YMMDD_Cadastro.csv', delimiter="\t", encoding="ISO-8859-9", low_memory=False) 

# iterando cada linha e procurando pelo nome
for i, row in data.iterrows():
    if  row['NOME']== str("LÍVIA ALMADA CRUZ RAFAEL") or row['NOME']==str("TICIANA LINHARES COELHO DA SILVA") or row['NOME']== str("MARIA VIVIANE DE MENEZES"): 
        print (data.loc[i,['Id_SERVIDOR_PORTAL','NOME', 'DESCRICAO_CARGO']])
        break
    else:
        pass
