### ISSUE TITLE
Substituir espaços em branco por underline e remover caracteres especiais

### ISSUE THREAD

**Issue by wendellmfm** [npi-ufc-qxd/dados-abertos#13]

**Comment by dnmendes76** [comment]
### Foi criado o Script para renomear os nomes das colunas, removendo caracteres especial e espaços em branco. Ao final é gerado um novo csv com as alterações.

![RenameRemuneracao.jpg](https://zube.io/files/npi-ufc-qxd/e397989bfe68695f40234b9fe751cd59.jpeg)

**Comment by crislanio** [comment]
![tirarCharEspecialCSVs.png](https://zube.io/files/npi-ufc-qxd/b261dab7790ed1be223696d369944c5a.png)

Ver em https://github.com/npi-ufc-qxd/dados-abertos/tree/master/Notebooks/TirarWSpaceCharSpecialcsv.ipynb e https://github.com/npi-ufc-qxd/dados-abertos/tree/master/Scripts/RenameColumns.py
