### ISSUE TITLE
Transformar string de cod_favorecido em inteiro

### ISSUE THREAD

**Issue by ticiana** [npi-ufc-qxd/dados-abertos#15]

**Comment by ticiana** [comment]
Por favor, providencie a explicação :-)

**Comment by Raul3212** [comment]
Cada caractere é mapeado para um inteiro de dois dígitos.
Os códigos são tratados como strings.
Caso um código seja composto somente por dígitos, ele é mantido, sendo apenas convertido para inteiro. Do contrário, cada caractere do código é convertido para o inteiro de dois dígitos correspondente.

**Comment by ticiana** [comment]
https://github.com/Nick-Lucas/godel-numbering-csharp

**Comment by Raul3212** [comment]
Esse é o resultado pro meu CPF:
158611257749146377152725282960177476153492448495910493595391264686123344168065122297424608726756979579189543243656577712286502876195919987990977816421264811443528001843082580583861724933163848307985523536802133670789206180725139697240959874870637297360220619018641827159099066408328766598655580077930254227690420978642892802567025670932965534996454221924973070997296995561583802719392450013918709259922753118388902043913558974891656301081253227630003926139982096410392883204060737829152075567621332143433887404652928440115768138789086482810086036298028414008893827404932884791593762615917436603550600498118612076002361774379701949525576375332405793042137651758743307081131962072352306382846582492279648836387338436982605675735460162987466540381995679166915449322278806426829900436483759844640529955445510815963360655310951517847321441057630233397422231248767849376677161499822736740693636730386034291076653277042305408106191437969746596433145096197456180612927286536802648180516517597731593155114561602680194006659466769554950360021796583465172992353736566201156569800952403587101234761068570652863402972728479300434666796254672921689734213058936636713329729545369890428163033333880055003387436391413110926813062389745268144330953297699077440325459297478411043263972398628664444853599440597096418035196109109240236695539889909757601910953553806416587155870084652078648481861060333185623402652485848796495644890804204957097221911848324550732157562421093556288499109066313140210376167874759823531103944465492858733565384971316980985443463401436228077083332027111768495706032711842957452849095181008740906885629349252948809921816305777702944154517979805132619803889526821033957001049516385286226600039920345320326470283809649514130314683746219549832343066190617793256108253101915778519651587955357005127996241902399612752563949796299051587423276117229828497685415892460906889103746846331941587403186924935697356652236549552696891914835258379884649559196782009724013928958302877946664575116228024100697982690689686043110104011006759583286486100257265210546819856055052360817124856048241640384764355892214068374696543439552220041195049785658576079091622322726280924015820736179041862986417625178174227244142010418108289814216851863888144691217143824391118486419724794913298803194223741889292994674423289520221805843147740734792793524210440764028268924694311761406521556940617471756099946218518555026521928917407121920935345811423281469350990217852983530864719956144001205699714289109533001303827895497551477826986482421471519624860334754432930349854184310346949096840731692890918116985641267077073018440497587607598897786459772336581284852755058842903722060988552066348035427531089119121838656786146602861526385335569707300016893231856317952294751052090958593393492693826981442018409254294335315709800769160024513048744781043856109506914706320797925096452611829662680664918321190945297369756331913262320004283842390196093303011792057204367339170550510966631894038960371698336337396677786079813682307757740038549841262948853174518690161250221564250132781546445617872693887597209403181757660967778664180449347257341623156826150893160326807977088503915932479651496122438666892120524855612051050356118143417075401672208685598182017805563743371812684582195524246092835365430693976781732361184969743450307725185849862758344421004597079798865904519847863884967135363009559305718030967131446217631820913010660322410354403438339101565303435171050899499468072670177656716119916358268685611900744587069513386522600470127551619251345239964126152388611955353015617329341885207990291892181349882275894979889571985997479705450701500439196245837241139243539397985332434191145868123638779738878077776409609679072126095141313686214174483019433421438309967709791931939913182093181425330297865301138049667952926633567285228562994082958211340696191310567475908707927188595219255932147312815582885850444377518418601
