### ISSUE TITLE
Pessoas sem Cargo, sem Função e sem Vínculo.

### ISSUE THREAD

**Issue by dnmendes76** [npi-ufc-qxd/dados-abertos#3]
Deve-se criar uma tabela para separar as pessoas que não tem cargo, não tem função e tem vínculo e uma tabela que não tem cargo, não tem função e não tem vínculo.

**Comment by dnmendes76** [comment]
## EXEMPLO DO CÓDIGO PARA GERAR AS TABELAS.

![qwe.jpg](https://zube.io/files/npi-ufc-qxd/706ef426a372bf278d3bcd4f0cfa2639.jpeg)

**Comment by crislanio** [comment]
## Com vínculo. Sem função. Sem cargo

![ComVinculoSFSC.png](https://zube.io/files/npi-ufc-qxd/6717f46e1c1bc689a1ccdebfad886c90.png)
## Sem vínculo. Sem função. Sem cargo
![semVSFSC.png](https://zube.io/files/npi-ufc-qxd/a8f07db080dec43cf16ed2d58b855474.png)

**Comment by wendellmfm** [comment]
Foi decidido que vamos criar 4 tabelas: Cargo, Função, Sem cargo sem função com vínculo, e ainda Sem cargo sem função sem vínculo.
